version: "3.8"

services:
  # ===========================
  # Aplicación SPA Completa
  # ===========================
  portal-abogados-spa:
    build:
      context: .
      dockerfile: Dockerfile.yml
    container_name: portal-abogados-spa
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MODE=production
      - STATIC_DIR=./portaldelabogado
      - DOMAIN=${DOMAIN:-portaldelabogado.com}
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/api/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - portal-network

  # ===========================
  # Base de Datos PostgreSQL
  # ===========================
  postgres:
    image: postgres:15-alpine
    container_name: portal-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-portal_abogados}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Uncomment para scripts de inicialización:
      # - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "127.0.0.1:5432:5432" # Solo acceso local por seguridad
    networks:
      - portal-network

  # ===========================
  # Redis para Cache
  # ===========================
  redis:
    image: redis:7-alpine
    container_name: portal-redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379" # Solo acceso local
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - portal-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  portal-network:
    driver: bridge
