#!/bin/bash
# Comandos rápidos para deployment Docker - DigitalOcean

echo "🐳 DEPLOYMENT DOCKER - COMANDOS RÁPIDOS"
echo "======================================"

echo ""
echo "🚀 1. DEPLOY COMPLETO EN 3 COMANDOS:"
echo "git clone https://github.com/TU_USUARIO/portaldeabogados.git"
echo "cd portaldeabogados && cp .env.production .env && nano .env"
echo "docker-compose up --build -d"

echo ""
echo "🔧 2. CONFIGURAR NGINX + SSL:"
echo "sudo apt install -y nginx certbot python3-certbot-nginx"
echo "sudo tee /etc/nginx/sites-available/portaldelabogado.com > /dev/null << 'EOF'"
echo "server {"
echo "    listen 80;"
echo "    server_name portaldelabogado.com www.portaldelabogado.com;"
echo "    location / {"
echo "        proxy_pass http://localhost:8080;"
echo "        proxy_set_header Host \$host;"
echo "        proxy_set_header X-Real-IP \$remote_addr;"
echo "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
echo "        proxy_set_header X-Forwarded-Proto \$scheme;"
echo "    }"
echo "}"
echo "EOF"
echo "sudo ln -s /etc/nginx/sites-available/portaldelabogado.com /etc/nginx/sites-enabled/"
echo "sudo rm -f /etc/nginx/sites-enabled/default"
echo "sudo nginx -t && sudo systemctl restart nginx"
echo "sudo certbot --nginx -d portaldelabogado.com -d www.portaldelabogado.com"

echo ""
echo "✅ 3. VERIFICAR:"
echo "curl https://portaldelabogado.com/api/health"
echo "docker-compose ps"
echo "docker-compose logs -f"

echo ""
echo "🔄 4. COMANDOS ÚTILES:"
echo "# Actualizar aplicación"
echo "git pull && docker-compose up --build -d"
echo ""
echo "# Ver logs"
echo "docker-compose logs -f portal-abogados-spa"
echo ""
echo "# Reiniciar"
echo "docker-compose restart"
echo ""
echo "# Ver estado"
echo "docker-compose ps"
echo ""
echo "# Backup"
echo "docker run --rm -v portaldeabogados_postgres_data:/data -v \$(pwd):/backup alpine tar czf /backup/postgres-backup.tar.gz -C /data ."

echo ""
echo "🎯 ¡LISTO! Tu Portal del Abogado estará en https://portaldelabogado.com"
